name: Build

on:
  push:
    tags:
      # Match any new tag
      - '*'

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        build:
          - { name: 'TorPlayer', os: 'macos-latest' }
          - { name: 'TorPlayer', os: 'ubuntu-latest' }
          - { name: 'TorPlayer', os: 'windows-latest' }

    runs-on: ${{ matrix.build.os }}
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Golang
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
      - run: go version
        shell: bash

      # ---- MacOS-------
      # Build MacOS
      - name: Build MacOS
        if: runner.os == 'macOS'
        run: |
          ./build/build-macos.sh $VERSION
        shell: bash
      # ---- End MacOS --------

      # ------ Windows --------
      # Build Windows
      - name: Build Windows
        if: runner.os == 'Windows'
        run: |
          .\build\build-windows.bat $env:VERSION
        shell: powershell
      # ------ End Windows -------

      # ----- Linux --------
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev
        shell: bash
      # Build Linux
      - name: Build Linux
        if: runner.os == 'Linux'
        run: |
          ./build/build-linux.sh $VERSION
        shell: bash
      # ----- End Linux -------

      # Upload build assets
      - uses: actions/upload-artifact@v4
        with:
          name: Build ${{matrix.build.name}} ${{runner.os}}
          path: |
            */bin/*.pkg
            */bin/*.deb
            *\bin\*.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*.pkg
            */bin/*.deb
            */bin/*.exe
